### ISSUE TITLE
请问还打算计划开源吗?

### ISSUE THREAD

**Issue by ghost** [XTeam-Wing/Vulcan#3]

**Comment by hi-KK** [comment]
估计是悬了

**Comment by XTeam-Wing** [comment]
这是毕设前匆忙写的1.0版本，系统用起来没问题但是代码不是很好，开源出来很渣，扔了又可惜。

**Comment by hi-KK** [comment]
> 这是毕设前匆忙写的1.0版本，系统用起来没问题但是代码不是很好，开源出来很渣，扔了又可惜。

其实可以整理整理开源出来的，也能给我们提供开发思路，架构设计还是比较合理的
